In [51]:
import pandas as pd
import numpy as np

In [52]:
dataset = pd.read_csv('../data/ethiopia.csv')

In [53]:
dataset['country'] = 'Ethiopia'
dataset.head

<bound method NDFrame.head of       YEAR  DOY    T2M  T2M_MAX  T2M_MIN  T2M_RANGE  PRECTOTCORR   RH2M  WS2M  \
0     2015    1  11.73    22.75     3.44      19.31         0.00  41.79  2.73
1     2015    2  12.30    24.01     4.09      19.92         0.00  33.29  2.39
2     2015    3  12.49    24.17     3.97      20.20         0.00  33.83  1.77
3     2015    4  14.08    23.78     6.90      16.88         0.00  38.84  0.87
4     2015    5  14.06    23.15     7.32      15.83         0.00  47.07  1.34
...    ...  ...    ...      ...      ...        ...          ...    ...   ...
4103  2026   86  16.99    24.29    11.80      12.49         5.27  73.87  1.79
4104  2026   87  15.29    19.58    12.08       7.50         6.46  80.85  1.13
4105  2026   88  16.28    22.34    11.69      10.65         9.53  77.96  1.30
4106  2026   89  17.66    25.31    11.08      14.23         0.85  68.88  2.02
4107  2026   90  18.25    26.36    12.14      14.22         0.40  63.95  2.18

      WS2M_MAX     PS   QV2M   country
0         5.07  77.13   4.00  Ethiopia
1         4.19  77.14   3.35  Ethiopia
2         2.76  77.11   3.43  Ethiopia
3         1.28  77.07   4.60  Ethiopia
4         2.14  77.01   5.58  Ethiopia
...        ...    ...    ...       ...
4103      3.09  76.60  11.17  Ethiopia
4104      2.35  76.59  11.29  Ethiopia
4105      2.39  76.48  11.42  Ethiopia
4106      3.80  76.44  10.64  Ethiopia
4107      3.64  76.47  10.14  Ethiopia

[4108 rows x 13 columns]>

In [54]:
dataset['Date'] = pd.to_datetime(dataset['YEAR']*1000 + dataset['DOY'],format='%Y%j')

In [55]:
dataset['Month'] = dataset['Date'].dt.month
dataset.head

<bound method NDFrame.head of       YEAR  DOY    T2M  T2M_MAX  T2M_MIN  T2M_RANGE  PRECTOTCORR   RH2M  WS2M  \
0     2015    1  11.73    22.75     3.44      19.31         0.00  41.79  2.73
1     2015    2  12.30    24.01     4.09      19.92         0.00  33.29  2.39
2     2015    3  12.49    24.17     3.97      20.20         0.00  33.83  1.77
3     2015    4  14.08    23.78     6.90      16.88         0.00  38.84  0.87
4     2015    5  14.06    23.15     7.32      15.83         0.00  47.07  1.34
...    ...  ...    ...      ...      ...        ...          ...    ...   ...
4103  2026   86  16.99    24.29    11.80      12.49         5.27  73.87  1.79
4104  2026   87  15.29    19.58    12.08       7.50         6.46  80.85  1.13
4105  2026   88  16.28    22.34    11.69      10.65         9.53  77.96  1.30
4106  2026   89  17.66    25.31    11.08      14.23         0.85  68.88  2.02
4107  2026   90  18.25    26.36    12.14      14.22         0.40  63.95  2.18

      WS2M_MAX     PS   QV2M   country       Date  Month
0         5.07  77.13   4.00  Ethiopia 2015-01-01      1
1         4.19  77.14   3.35  Ethiopia 2015-01-02      1
2         2.76  77.11   3.43  Ethiopia 2015-01-03      1
3         1.28  77.07   4.60  Ethiopia 2015-01-04      1
4         2.14  77.01   5.58  Ethiopia 2015-01-05      1
...        ...    ...    ...       ...        ...    ...
4103      3.09  76.60  11.17  Ethiopia 2026-03-27      3
4104      2.35  76.59  11.29  Ethiopia 2026-03-28      3
4105      2.39  76.48  11.42  Ethiopia 2026-03-29      3
4106      3.80  76.44  10.64  Ethiopia 2026-03-30      3
4107      3.64  76.47  10.14  Ethiopia 2026-03-31      3

[4108 rows x 15 columns]>

In [56]:
dataset.replace(-999,np.nan, inplace=True)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,country,Date,Month
0,2015,1,11.73,22.75,3.44,19.31,0.00,41.79,2.73,5.07,77.13,4.00,Ethiopia,2015-01-01,1
1,2015,2,12.30,24.01,4.09,19.92,0.00,33.29,2.39,4.19,77.14,3.35,Ethiopia,2015-01-02,1
2,2015,3,12.49,24.17,3.97,20.20,0.00,33.83,1.77,2.76,77.11,3.43,Ethiopia,2015-01-03,1
3,2015,4,14.08,23.78,6.90,16.88,0.00,38.84,0.87,1.28,77.07,4.60,Ethiopia,2015-01-04,1
4,2015,5,14.06,23.15,7.32,15.83,0.00,47.07,1.34,2.14,77.01,5.58,Ethiopia,2015-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4103,2026,86,16.99,24.29,11.80,12.49,5.27,73.87,1.79,3.09,76.60,11.17,Ethiopia,2026-03-27,3
4104,2026,87,15.29,19.58,12.08,7.50,6.46,80.85,1.13,2.35,76.59,11.29,Ethiopia,2026-03-28,3
4105,2026,88,16.28,22.34,11.69,10.65,9.53,77.96,1.30,2.39,76.48,11.42,Ethiopia,2026-03-29,3
4106,2026,89,17.66,25.31,11.08,14.23,0.85,68.88,2.02,3.80,76.44,10.64,Ethiopia,2026-03-30,3
4107,2026,90,18.25,26.36,12.14,14.22,0.40,63.95,2.18,3.64,76.47,10.14,Ethiopia,2026-03-31,3

In [57]:
dataset.duplicated().sum()

np.int64(0)

In [58]:
dataset.describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Date,Month
count,4108.000000,4108.000000,4108.00000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108,4108.000000
mean,2020.131451,180.121227,16.06850,23.199175,10.227544,12.971631,3.633795,68.408588,1.979998,3.575246,77.037529,9.697724,2020-08-15 12:00:00,6.423564
min,2015.000000,1.000000,10.03000,15.650000,1.170000,3.560000,0.000000,14.420000,0.460000,0.790000,76.360000,2.120000,2015-01-01 00:00:00,1.000000
25%,2017.000000,86.000000,14.82000,21.110000,8.417500,9.830000,0.020000,59.030000,1.407500,2.720000,76.980000,8.070000,2017-10-23 18:00:00,3.000000
50%,2020.000000,179.000000,16.04000,22.740000,10.990000,13.030000,0.820000,71.120000,1.970000,3.530000,77.040000,10.270000,2020-08-15 12:00:00,6.000000
75%,2023.000000,272.000000,17.36000,25.170000,12.220000,16.020000,4.580000,80.802500,2.480000,4.370000,77.100000,11.710000,2023-06-08 06:00:00,9.000000
max,2026.000000,366.000000,21.53000,30.930000,15.680000,23.240000,82.300000,91.930000,4.130000,7.490000,77.370000,13.520000,2026-03-31 00:00:00,12.000000
std,3.248907,106.294767,1.89805,2.751471,2.607256,3.821239,6.289061,14.735838,0.689093,1.123721,0.099484,2.362462,NaN,3.477046

In [59]:
duplicates = dataset.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")
if duplicates > 0:
    dataset.drop_duplicates(inplace=True)
    print("Duplicates dropped.")
# Note: df.duplicated() checks entire rows; if duplicates exist, they span all columns.

Number of duplicate rows: 0

In [60]:
numeric_cols = dataset.select_dtypes(include=[np.number]).columns
dataset[numeric_cols].describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Month
count,4108.000000,4108.000000,4108.00000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000
mean,2020.131451,180.121227,16.06850,23.199175,10.227544,12.971631,3.633795,68.408588,1.979998,3.575246,77.037529,9.697724,6.423564
std,3.248907,106.294767,1.89805,2.751471,2.607256,3.821239,6.289061,14.735838,0.689093,1.123721,0.099484,2.362462,3.477046
min,2015.000000,1.000000,10.03000,15.650000,1.170000,3.560000,0.000000,14.420000,0.460000,0.790000,76.360000,2.120000,1.000000
25%,2017.000000,86.000000,14.82000,21.110000,8.417500,9.830000,0.020000,59.030000,1.407500,2.720000,76.980000,8.070000,3.000000
50%,2020.000000,179.000000,16.04000,22.740000,10.990000,13.030000,0.820000,71.120000,1.970000,3.530000,77.040000,10.270000,6.000000
75%,2023.000000,272.000000,17.36000,25.170000,12.220000,16.020000,4.580000,80.802500,2.480000,4.370000,77.100000,11.710000,9.000000
max,2026.000000,366.000000,21.53000,30.930000,15.680000,23.240000,82.300000,91.930000,4.130000,7.490000,77.370000,13.520000,12.000000

In [61]:
missing = dataset.isna().sum()
missing_pct = (missing / len(dataset)) * 100
print(missing_pct)
high_missing = missing_pct[missing_pct > 5]
print(f"Columns with >5% missing: {list(high_missing.index)}")
# Interpretation: High missing values (e.g., >5%) may indicate data collection gaps, sensor failures, or regional unavailability, potentially biasing analysis if not handled (e.g., via imputation or exclusion).

YEAR           0.0
DOY            0.0
T2M            0.0
T2M_MAX        0.0
T2M_MIN        0.0
T2M_RANGE      0.0
PRECTOTCORR    0.0
RH2M           0.0
WS2M           0.0
WS2M_MAX       0.0
PS             0.0
QV2M           0.0
country        0.0
Date           0.0
Month          0.0
dtype: float64
Columns with >5% missing: []

In [62]:
cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']
z_scores = (dataset[cols] - dataset[cols].mean()) / dataset[cols].std(ddof=0)
outlier_mask = np.abs(z_scores) > 3
outlier_count = outlier_mask.any(axis=1).sum()

print(f"Rows with |Z| > 3: {outlier_count}")

Rows with |Z| > 3: 132

In [63]:
outlier_rows = dataset[outlier_mask.any(axis=1)]
outlier_rows[['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']].head()

       T2M  T2M_MAX  T2M_MIN  PRECTOTCORR   RH2M  WS2M  WS2M_MAX
144  18.45    24.94    14.15        29.07  68.37  1.52      3.07
145  17.60    23.52    13.22        34.38  75.91  1.66      3.53
177  15.79    19.03    13.33        23.89  83.89  1.81      3.03
214  15.97    21.06    12.58        23.46  84.73  1.58      2.55
556  15.20    18.00    12.89        25.19  85.47  1.33      2.99

In [64]:
weather_cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']
dataset[weather_cols] = dataset[weather_cols].ffill()

In [65]:
threshold = int(0.3 * len(dataset.columns))
dataset = dataset.dropna(thresh=len(dataset.columns) - threshold)

In [66]:
row_missing_pct = dataset.isna().mean(axis=1)
dataset = dataset[row_missing_pct <= 0.30]

In [67]:
dataset.to_csv('../data/ethiopia_clean.csv', index=False)