In [18]:
import pandas as pd
import numpy as np

In [19]:
dataset = pd.read_csv('../data/nigeria.csv')

In [20]:
dataset['country'] = 'Nigeria'
dataset.head

<bound method NDFrame.head of       YEAR  DOY    T2M  T2M_MAX  T2M_MIN  T2M_RANGE  PRECTOTCORR   RH2M  WS2M  \
0     2015    1  25.23    29.25    22.06       7.19         0.00  68.26  1.73
1     2015    2  26.16    29.41    22.87       6.54         0.00  73.23  1.42
2     2015    3  25.66    29.02    22.63       6.39         0.00  78.71  1.69
3     2015    4  24.11    27.27    19.92       7.35         0.00  63.66  2.15
4     2015    5  23.40    27.28    18.18       9.10         0.00  59.45  1.88
...    ...  ...    ...      ...      ...        ...          ...    ...   ...
4103  2026   86  29.05    32.43    26.69       5.74         2.82  76.60  2.35
4104  2026   87  28.72    31.98    27.14       4.84         5.19  79.61  2.55
4105  2026   88  27.72    29.53    26.21       3.32         1.43  82.83  1.10
4106  2026   89  28.42    31.17    26.36       4.81         0.85  77.73  2.30
4107  2026   90  28.40    31.73    26.32       5.41         5.33  78.79  1.76

      WS2M_MAX      PS   QV2M  country
0         2.61  100.86  13.36  Nigeria
1         1.95  100.94  15.37  Nigeria
2         2.33  101.06  15.98  Nigeria
3         3.80  101.09  11.65  Nigeria
4         3.48  101.03  10.40  Nigeria
...        ...     ...    ...      ...
4103      3.39  100.58  19.10  Nigeria
4104      3.17  100.64  19.49  Nigeria
4105      1.78  100.61  19.22  Nigeria
4106      3.40  100.53  18.73  Nigeria
4107      2.80  100.59  18.94  Nigeria

[4108 rows x 13 columns]>

In [21]:
dataset['Date'] = pd.to_datetime(dataset['YEAR']*1000 + dataset['DOY'],format='%Y%j')

In [22]:
dataset['Month'] = dataset['Date'].dt.month
dataset.head

<bound method NDFrame.head of       YEAR  DOY    T2M  T2M_MAX  T2M_MIN  T2M_RANGE  PRECTOTCORR   RH2M  WS2M  \
0     2015    1  25.23    29.25    22.06       7.19         0.00  68.26  1.73
1     2015    2  26.16    29.41    22.87       6.54         0.00  73.23  1.42
2     2015    3  25.66    29.02    22.63       6.39         0.00  78.71  1.69
3     2015    4  24.11    27.27    19.92       7.35         0.00  63.66  2.15
4     2015    5  23.40    27.28    18.18       9.10         0.00  59.45  1.88
...    ...  ...    ...      ...      ...        ...          ...    ...   ...
4103  2026   86  29.05    32.43    26.69       5.74         2.82  76.60  2.35
4104  2026   87  28.72    31.98    27.14       4.84         5.19  79.61  2.55
4105  2026   88  27.72    29.53    26.21       3.32         1.43  82.83  1.10
4106  2026   89  28.42    31.17    26.36       4.81         0.85  77.73  2.30
4107  2026   90  28.40    31.73    26.32       5.41         5.33  78.79  1.76

      WS2M_MAX      PS   QV2M  country       Date  Month
0         2.61  100.86  13.36  Nigeria 2015-01-01      1
1         1.95  100.94  15.37  Nigeria 2015-01-02      1
2         2.33  101.06  15.98  Nigeria 2015-01-03      1
3         3.80  101.09  11.65  Nigeria 2015-01-04      1
4         3.48  101.03  10.40  Nigeria 2015-01-05      1
...        ...     ...    ...      ...        ...    ...
4103      3.39  100.58  19.10  Nigeria 2026-03-27      3
4104      3.17  100.64  19.49  Nigeria 2026-03-28      3
4105      1.78  100.61  19.22  Nigeria 2026-03-29      3
4106      3.40  100.53  18.73  Nigeria 2026-03-30      3
4107      2.80  100.59  18.94  Nigeria 2026-03-31      3

[4108 rows x 15 columns]>

In [23]:
dataset.replace(-999,np.nan, inplace=True)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,country,Date,Month
0,2015,1,25.23,29.25,22.06,7.19,0.00,68.26,1.73,2.61,100.86,13.36,Nigeria,2015-01-01,1
1,2015,2,26.16,29.41,22.87,6.54,0.00,73.23,1.42,1.95,100.94,15.37,Nigeria,2015-01-02,1
2,2015,3,25.66,29.02,22.63,6.39,0.00,78.71,1.69,2.33,101.06,15.98,Nigeria,2015-01-03,1
3,2015,4,24.11,27.27,19.92,7.35,0.00,63.66,2.15,3.80,101.09,11.65,Nigeria,2015-01-04,1
4,2015,5,23.40,27.28,18.18,9.10,0.00,59.45,1.88,3.48,101.03,10.40,Nigeria,2015-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4103,2026,86,29.05,32.43,26.69,5.74,2.82,76.60,2.35,3.39,100.58,19.10,Nigeria,2026-03-27,3
4104,2026,87,28.72,31.98,27.14,4.84,5.19,79.61,2.55,3.17,100.64,19.49,Nigeria,2026-03-28,3
4105,2026,88,27.72,29.53,26.21,3.32,1.43,82.83,1.10,1.78,100.61,19.22,Nigeria,2026-03-29,3
4106,2026,89,28.42,31.17,26.36,4.81,0.85,77.73,2.30,3.40,100.53,18.73,Nigeria,2026-03-30,3
4107,2026,90,28.40,31.73,26.32,5.41,5.33,78.79,1.76,2.80,100.59,18.94,Nigeria,2026-03-31,3

In [24]:
dataset.duplicated().sum()

np.int64(0)

In [25]:
dataset.describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Date,Month
count,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108,4108.000000
mean,2020.131451,180.121227,26.656928,28.914667,24.886461,4.028206,4.213914,85.237040,2.217135,2.903335,100.827205,18.558505,2020-08-15 12:00:00,6.423564
min,2015.000000,1.000000,21.120000,25.260000,15.170000,1.160000,0.000000,54.400000,0.740000,1.290000,100.380000,9.430000,2015-01-01 00:00:00,1.000000
25%,2017.000000,86.000000,25.720000,27.920000,24.100000,3.090000,0.330000,83.930000,1.770000,2.370000,100.710000,17.970000,2017-10-23 18:00:00,3.000000
50%,2020.000000,179.000000,26.820000,28.990000,25.100000,3.770000,1.840000,86.350000,2.200000,2.810000,100.820000,18.840000,2020-08-15 12:00:00,6.000000
75%,2023.000000,272.000000,27.540000,29.910000,25.860000,4.600000,5.200000,88.500000,2.630000,3.390000,100.950000,19.570000,2023-06-08 06:00:00,9.000000
max,2026.000000,366.000000,29.290000,32.880000,27.790000,11.730000,166.100000,93.790000,4.780000,6.000000,101.350000,21.740000,2026-03-31 00:00:00,12.000000
std,3.248907,106.294767,1.123335,1.294345,1.396727,1.399169,7.266742,5.446007,0.587191,0.696885,0.165321,1.646313,NaN,3.477046

In [26]:
duplicates = dataset.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")
if duplicates > 0:
    dataset.drop_duplicates(inplace=True)
    print("Duplicates dropped.")
# Note: df.duplicated() checks entire rows; if duplicates exist, they span all columns.

Number of duplicate rows: 0

In [27]:
numeric_cols = dataset.select_dtypes(include=[np.number]).columns
dataset[numeric_cols].describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Month
count,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000
mean,2020.131451,180.121227,26.656928,28.914667,24.886461,4.028206,4.213914,85.237040,2.217135,2.903335,100.827205,18.558505,6.423564
std,3.248907,106.294767,1.123335,1.294345,1.396727,1.399169,7.266742,5.446007,0.587191,0.696885,0.165321,1.646313,3.477046
min,2015.000000,1.000000,21.120000,25.260000,15.170000,1.160000,0.000000,54.400000,0.740000,1.290000,100.380000,9.430000,1.000000
25%,2017.000000,86.000000,25.720000,27.920000,24.100000,3.090000,0.330000,83.930000,1.770000,2.370000,100.710000,17.970000,3.000000
50%,2020.000000,179.000000,26.820000,28.990000,25.100000,3.770000,1.840000,86.350000,2.200000,2.810000,100.820000,18.840000,6.000000
75%,2023.000000,272.000000,27.540000,29.910000,25.860000,4.600000,5.200000,88.500000,2.630000,3.390000,100.950000,19.570000,9.000000
max,2026.000000,366.000000,29.290000,32.880000,27.790000,11.730000,166.100000,93.790000,4.780000,6.000000,101.350000,21.740000,12.000000

In [28]:
missing = dataset.isna().sum()
missing_pct = (missing / len(dataset)) * 100
print(missing_pct)
high_missing = missing_pct[missing_pct > 5]
print(f"Columns with >5% missing: {list(high_missing.index)}")
# Interpretation: High missing values (e.g., >5%) may indicate data collection gaps, sensor failures, or regional unavailability, potentially biasing analysis if not handled (e.g., via imputation or exclusion).

YEAR           0.0
DOY            0.0
T2M            0.0
T2M_MAX        0.0
T2M_MIN        0.0
T2M_RANGE      0.0
PRECTOTCORR    0.0
RH2M           0.0
WS2M           0.0
WS2M_MAX       0.0
PS             0.0
QV2M           0.0
country        0.0
Date           0.0
Month          0.0
dtype: float64
Columns with >5% missing: []

In [29]:
cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']
z_scores = (dataset[cols] - dataset[cols].mean()) / dataset[cols].std(ddof=0)
outlier_mask = np.abs(z_scores) > 3
outlier_count = outlier_mask.any(axis=1).sum()

print(f"Rows with |Z| > 3: {outlier_count}")

Rows with |Z| > 3: 225

In [30]:
outlier_rows = dataset[outlier_mask.any(axis=1)]
outlier_rows[['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']].head()

     T2M  T2M_MAX  T2M_MIN  PRECTOTCORR   RH2M  WS2M  WS2M_MAX
0  25.23    29.25    22.06          0.0  68.26  1.73      2.61
3  24.11    27.27    19.92          0.0  63.66  2.15      3.80
4  23.40    27.28    18.18          0.0  59.45  1.88      3.48
5  22.66    25.77    18.03          0.0  62.57  1.37      2.10
6  23.53    26.36    20.21          0.0  61.92  1.57      2.43

In [31]:
weather_cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']
dataset[weather_cols] = dataset[weather_cols].ffill()

In [32]:
threshold = int(0.3 * len(dataset.columns))
dataset = dataset.dropna(thresh=len(dataset.columns) - threshold)

In [33]:
row_missing_pct = dataset.isna().mean(axis=1)
dataset = dataset[row_missing_pct <= 0.30]

In [34]:
dataset.to_csv('../data/nigeria_clean.csv', index=False)