In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('../data/sudan.csv')

In [3]:
dataset['country'] = 'Sudan'
dataset.head

<bound method NDFrame.head of       YEAR  DOY    T2M  T2M_MAX  T2M_MIN  T2M_RANGE  PRECTOTCORR   RH2M  WS2M  \
0     2015    1  25.18    35.55    16.14      19.41          0.0  31.87  3.46
1     2015    2  23.92    34.14    15.81      18.33          0.0  23.83  4.24
2     2015    3  22.73    31.64    15.09      16.55          0.0  38.21  5.01
3     2015    4  19.15    27.35    12.88      14.47          0.0  21.07  5.72
4     2015    5  17.54    27.22     9.49      17.73          0.0  21.58  4.28
...    ...  ...    ...      ...      ...        ...          ...    ...   ...
4103  2026   86  27.89    34.69    21.67      13.02          0.0  14.47  3.66
4104  2026   87  28.73    36.61    21.34      15.27          0.0   9.75  3.21
4105  2026   88  30.06    38.89    21.15      17.74          0.0  11.63  2.41
4106  2026   89  32.50    41.53    23.61      17.92          0.0  14.06  2.81
4107  2026   90  33.79    42.64    25.73      16.91          0.0  13.89  3.52

      WS2M_MAX     PS  QV2M country
0         5.12  96.54  6.08   Sudan
1         5.10  96.67  4.31   Sudan
2         6.24  96.77  6.42   Sudan
3         6.96  96.93  3.06   Sudan
4         5.82  96.85  2.86   Sudan
...        ...    ...   ...     ...
4103      5.11  96.47  3.52   Sudan
4104      4.40  96.35  2.44   Sudan
4105      3.87  96.10  3.12   Sudan
4106      4.87  95.93  4.18   Sudan
4107      5.00  95.89  4.47   Sudan

[4108 rows x 13 columns]>

In [4]:
dataset['Date'] = pd.to_datetime(dataset['YEAR']*1000 + dataset['DOY'],format='%Y%j')

In [5]:
dataset['Month'] = dataset['Date'].dt.month
dataset.head

<bound method NDFrame.head of       YEAR  DOY    T2M  T2M_MAX  T2M_MIN  T2M_RANGE  PRECTOTCORR   RH2M  WS2M  \
0     2015    1  25.18    35.55    16.14      19.41          0.0  31.87  3.46
1     2015    2  23.92    34.14    15.81      18.33          0.0  23.83  4.24
2     2015    3  22.73    31.64    15.09      16.55          0.0  38.21  5.01
3     2015    4  19.15    27.35    12.88      14.47          0.0  21.07  5.72
4     2015    5  17.54    27.22     9.49      17.73          0.0  21.58  4.28
...    ...  ...    ...      ...      ...        ...          ...    ...   ...
4103  2026   86  27.89    34.69    21.67      13.02          0.0  14.47  3.66
4104  2026   87  28.73    36.61    21.34      15.27          0.0   9.75  3.21
4105  2026   88  30.06    38.89    21.15      17.74          0.0  11.63  2.41
4106  2026   89  32.50    41.53    23.61      17.92          0.0  14.06  2.81
4107  2026   90  33.79    42.64    25.73      16.91          0.0  13.89  3.52

      WS2M_MAX     PS  QV2M country       Date  Month
0         5.12  96.54  6.08   Sudan 2015-01-01      1
1         5.10  96.67  4.31   Sudan 2015-01-02      1
2         6.24  96.77  6.42   Sudan 2015-01-03      1
3         6.96  96.93  3.06   Sudan 2015-01-04      1
4         5.82  96.85  2.86   Sudan 2015-01-05      1
...        ...    ...   ...     ...        ...    ...
4103      5.11  96.47  3.52   Sudan 2026-03-27      3
4104      4.40  96.35  2.44   Sudan 2026-03-28      3
4105      3.87  96.10  3.12   Sudan 2026-03-29      3
4106      4.87  95.93  4.18   Sudan 2026-03-30      3
4107      5.00  95.89  4.47   Sudan 2026-03-31      3

[4108 rows x 15 columns]>

In [6]:
dataset.replace(-999,np.nan, inplace=True)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,country,Date,Month
0,2015,1,25.18,35.55,16.14,19.41,0.0,31.87,3.46,5.12,96.54,6.08,Sudan,2015-01-01,1
1,2015,2,23.92,34.14,15.81,18.33,0.0,23.83,4.24,5.10,96.67,4.31,Sudan,2015-01-02,1
2,2015,3,22.73,31.64,15.09,16.55,0.0,38.21,5.01,6.24,96.77,6.42,Sudan,2015-01-03,1
3,2015,4,19.15,27.35,12.88,14.47,0.0,21.07,5.72,6.96,96.93,3.06,Sudan,2015-01-04,1
4,2015,5,17.54,27.22,9.49,17.73,0.0,21.58,4.28,5.82,96.85,2.86,Sudan,2015-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4103,2026,86,27.89,34.69,21.67,13.02,0.0,14.47,3.66,5.11,96.47,3.52,Sudan,2026-03-27,3
4104,2026,87,28.73,36.61,21.34,15.27,0.0,9.75,3.21,4.40,96.35,2.44,Sudan,2026-03-28,3
4105,2026,88,30.06,38.89,21.15,17.74,0.0,11.63,2.41,3.87,96.10,3.12,Sudan,2026-03-29,3
4106,2026,89,32.50,41.53,23.61,17.92,0.0,14.06,2.81,4.87,95.93,4.18,Sudan,2026-03-30,3
4107,2026,90,33.79,42.64,25.73,16.91,0.0,13.89,3.52,5.00,95.89,4.47,Sudan,2026-03-31,3

In [7]:
dataset.duplicated().sum()

np.int64(0)

In [8]:
dataset.describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Date,Month
count,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108,4108.000000
mean,2020.131451,180.121227,28.759007,36.773914,21.508510,15.265404,0.643875,31.359192,3.484253,5.157378,96.346273,7.864557,2020-08-15 12:00:00,6.423564
min,2015.000000,1.000000,13.180000,21.040000,5.930000,3.420000,0.000000,4.690000,0.610000,1.030000,95.660000,1.160000,2015-01-01 00:00:00,1.000000
25%,2017.000000,86.000000,25.560000,33.730000,17.497500,13.280000,0.000000,17.407500,2.730000,4.267500,96.160000,3.730000,2017-10-23 18:00:00,3.000000
50%,2020.000000,179.000000,29.160000,37.020000,22.890000,15.810000,0.000000,26.630000,3.490000,5.120000,96.310000,5.895000,2020-08-15 12:00:00,6.000000
75%,2023.000000,272.000000,32.510000,40.330000,25.430000,17.680000,0.010000,40.535000,4.220000,6.020000,96.510000,12.500000,2023-06-08 06:00:00,9.000000
max,2026.000000,366.000000,37.990000,45.960000,32.170000,22.480000,66.490000,87.160000,7.150000,9.050000,97.310000,19.440000,2026-03-31 00:00:00,12.000000
std,3.248907,106.294767,4.681305,4.400065,5.091142,3.298919,3.057672,17.851849,1.040667,1.280238,0.266927,4.880934,NaN,3.477046

In [9]:
duplicates = dataset.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")
if duplicates > 0:
    dataset.drop_duplicates(inplace=True)
    print("Duplicates dropped.")
# Note: df.duplicated() checks entire rows; if duplicates exist, they span all columns.

Number of duplicate rows: 0

In [10]:
numeric_cols = dataset.select_dtypes(include=[np.number]).columns
dataset[numeric_cols].describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Month
count,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000
mean,2020.131451,180.121227,28.759007,36.773914,21.508510,15.265404,0.643875,31.359192,3.484253,5.157378,96.346273,7.864557,6.423564
std,3.248907,106.294767,4.681305,4.400065,5.091142,3.298919,3.057672,17.851849,1.040667,1.280238,0.266927,4.880934,3.477046
min,2015.000000,1.000000,13.180000,21.040000,5.930000,3.420000,0.000000,4.690000,0.610000,1.030000,95.660000,1.160000,1.000000
25%,2017.000000,86.000000,25.560000,33.730000,17.497500,13.280000,0.000000,17.407500,2.730000,4.267500,96.160000,3.730000,3.000000
50%,2020.000000,179.000000,29.160000,37.020000,22.890000,15.810000,0.000000,26.630000,3.490000,5.120000,96.310000,5.895000,6.000000
75%,2023.000000,272.000000,32.510000,40.330000,25.430000,17.680000,0.010000,40.535000,4.220000,6.020000,96.510000,12.500000,9.000000
max,2026.000000,366.000000,37.990000,45.960000,32.170000,22.480000,66.490000,87.160000,7.150000,9.050000,97.310000,19.440000,12.000000

In [11]:
missing = dataset.isna().sum()
missing_pct = (missing / len(dataset)) * 100
print(missing_pct)
high_missing = missing_pct[missing_pct > 5]
print(f"Columns with >5% missing: {list(high_missing.index)}")
# Interpretation: High missing values (e.g., >5%) may indicate data collection gaps, sensor failures, or regional unavailability, potentially biasing analysis if not handled (e.g., via imputation or exclusion).

YEAR           0.0
DOY            0.0
T2M            0.0
T2M_MAX        0.0
T2M_MIN        0.0
T2M_RANGE      0.0
PRECTOTCORR    0.0
RH2M           0.0
WS2M           0.0
WS2M_MAX       0.0
PS             0.0
QV2M           0.0
country        0.0
Date           0.0
Month          0.0
dtype: float64
Columns with >5% missing: []

In [12]:
cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']
z_scores = (dataset[cols] - dataset[cols].mean()) / dataset[cols].std(ddof=0)
outlier_mask = np.abs(z_scores) > 3
outlier_count = outlier_mask.any(axis=1).sum()

print(f"Rows with |Z| > 3: {outlier_count}")

Rows with |Z| > 3: 84

In [13]:
outlier_rows = dataset[outlier_mask.any(axis=1)]
outlier_rows[['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']].head()

       T2M  T2M_MAX  T2M_MIN  PRECTOTCORR   RH2M  WS2M  WS2M_MAX
8    14.29    22.39     7.83         0.00  23.46  5.58      7.90
9    13.18    21.04     6.59         0.00  32.34  5.03      7.66
10   14.21    23.32     5.93         0.00  30.62  4.36      6.15
223  32.64    41.23    25.96        23.61  48.05  4.65      8.41
392  14.76    23.33     7.42         0.00  24.26  4.49      6.86

In [14]:
weather_cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']
dataset[weather_cols] = dataset[weather_cols].ffill()

In [15]:
threshold = int(0.3 * len(dataset.columns))
dataset = dataset.dropna(thresh=len(dataset.columns) - threshold)

In [16]:
row_missing_pct = dataset.isna().mean(axis=1)
dataset = dataset[row_missing_pct <= 0.30]

In [17]:
dataset.to_csv('../data/sudan_clean.csv', index=False)