In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('../data/tanzania.csv')

In [3]:
dataset['country'] = 'Tanzania'
dataset.head

<bound method NDFrame.head of       YEAR  DOY    T2M  T2M_MAX  T2M_MIN  T2M_RANGE  PRECTOTCORR   RH2M  WS2M  \
0     2015    1  27.56    29.52    26.22       3.30         7.24  80.97  4.68
1     2015    2  27.59    29.99    25.92       4.07         3.40  79.63  4.48
2     2015    3  27.47    29.29    26.25       3.04         7.17  80.02  4.91
3     2015    4  27.28    29.17    25.96       3.21        16.07  81.78  4.88
4     2015    5  26.68    27.83    25.84       1.99        18.83  82.99  4.17
...    ...  ...    ...      ...      ...        ...          ...    ...   ...
4103  2026   86  27.63    30.65    25.66       4.99         2.96  77.48  1.57
4104  2026   87  27.51    31.23    24.84       6.39         1.65  77.72  1.36
4105  2026   88  27.74    31.21    25.33       5.88         1.28  77.35  1.53
4106  2026   89  27.83    31.29    25.31       5.98         0.92  76.50  1.64
4107  2026   90  28.14    31.55    26.06       5.49         0.83  74.46  1.35

      WS2M_MAX      PS   QV2M   country
0         6.01  100.52  18.61  Tanzania
1         5.28  100.52  18.31  Tanzania
2         5.99  100.56  18.30  Tanzania
3         6.07  100.47  18.52  Tanzania
4         5.98  100.43  18.16  Tanzania
...        ...     ...    ...       ...
4103      2.40  100.73  17.72  Tanzania
4104      1.79  100.61  17.59  Tanzania
4105      2.01  100.42  17.81  Tanzania
4106      2.15  100.43  17.72  Tanzania
4107      1.90  100.47  17.56  Tanzania

[4108 rows x 13 columns]>

In [4]:
dataset['Date'] = pd.to_datetime(dataset['YEAR']*1000 + dataset['DOY'],format='%Y%j')

In [5]:
dataset['Month'] = dataset['Date'].dt.month
dataset.head

<bound method NDFrame.head of       YEAR  DOY    T2M  T2M_MAX  T2M_MIN  T2M_RANGE  PRECTOTCORR   RH2M  WS2M  \
0     2015    1  27.56    29.52    26.22       3.30         7.24  80.97  4.68
1     2015    2  27.59    29.99    25.92       4.07         3.40  79.63  4.48
2     2015    3  27.47    29.29    26.25       3.04         7.17  80.02  4.91
3     2015    4  27.28    29.17    25.96       3.21        16.07  81.78  4.88
4     2015    5  26.68    27.83    25.84       1.99        18.83  82.99  4.17
...    ...  ...    ...      ...      ...        ...          ...    ...   ...
4103  2026   86  27.63    30.65    25.66       4.99         2.96  77.48  1.57
4104  2026   87  27.51    31.23    24.84       6.39         1.65  77.72  1.36
4105  2026   88  27.74    31.21    25.33       5.88         1.28  77.35  1.53
4106  2026   89  27.83    31.29    25.31       5.98         0.92  76.50  1.64
4107  2026   90  28.14    31.55    26.06       5.49         0.83  74.46  1.35

      WS2M_MAX      PS   QV2M   country       Date  Month
0         6.01  100.52  18.61  Tanzania 2015-01-01      1
1         5.28  100.52  18.31  Tanzania 2015-01-02      1
2         5.99  100.56  18.30  Tanzania 2015-01-03      1
3         6.07  100.47  18.52  Tanzania 2015-01-04      1
4         5.98  100.43  18.16  Tanzania 2015-01-05      1
...        ...     ...    ...       ...        ...    ...
4103      2.40  100.73  17.72  Tanzania 2026-03-27      3
4104      1.79  100.61  17.59  Tanzania 2026-03-28      3
4105      2.01  100.42  17.81  Tanzania 2026-03-29      3
4106      2.15  100.43  17.72  Tanzania 2026-03-30      3
4107      1.90  100.47  17.56  Tanzania 2026-03-31      3

[4108 rows x 15 columns]>

In [6]:
dataset.replace(-999,np.nan, inplace=True)

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,country,Date,Month
0,2015,1,27.56,29.52,26.22,3.30,7.24,80.97,4.68,6.01,100.52,18.61,Tanzania,2015-01-01,1
1,2015,2,27.59,29.99,25.92,4.07,3.40,79.63,4.48,5.28,100.52,18.31,Tanzania,2015-01-02,1
2,2015,3,27.47,29.29,26.25,3.04,7.17,80.02,4.91,5.99,100.56,18.30,Tanzania,2015-01-03,1
3,2015,4,27.28,29.17,25.96,3.21,16.07,81.78,4.88,6.07,100.47,18.52,Tanzania,2015-01-04,1
4,2015,5,26.68,27.83,25.84,1.99,18.83,82.99,4.17,5.98,100.43,18.16,Tanzania,2015-01-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4103,2026,86,27.63,30.65,25.66,4.99,2.96,77.48,1.57,2.40,100.73,17.72,Tanzania,2026-03-27,3
4104,2026,87,27.51,31.23,24.84,6.39,1.65,77.72,1.36,1.79,100.61,17.59,Tanzania,2026-03-28,3
4105,2026,88,27.74,31.21,25.33,5.88,1.28,77.35,1.53,2.01,100.42,17.81,Tanzania,2026-03-29,3
4106,2026,89,27.83,31.29,25.31,5.98,0.92,76.50,1.64,2.15,100.43,17.72,Tanzania,2026-03-30,3
4107,2026,90,28.14,31.55,26.06,5.49,0.83,74.46,1.35,1.90,100.47,17.56,Tanzania,2026-03-31,3

In [7]:
dataset.duplicated().sum()

np.int64(0)

In [8]:
dataset.describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Date,Month
count,4108.000000,4108.000000,4108.000000,4108.000000,4108.00000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108,4108.000000
mean,2020.131451,180.121227,26.802422,29.163493,25.03813,4.125363,3.740256,77.128038,4.105370,5.189248,100.801130,16.923683,2020-08-15 12:00:00,6.423564
min,2015.000000,1.000000,22.680000,25.410000,20.03000,0.940000,0.000000,60.060000,1.120000,1.550000,100.150000,11.380000,2015-01-01 00:00:00,1.000000
25%,2017.000000,86.000000,25.670000,28.090000,23.71000,3.330000,0.110000,73.167500,3.410000,4.377500,100.570000,15.340000,2017-10-23 18:00:00,3.000000
50%,2020.000000,179.000000,26.990000,29.080000,25.37500,4.220000,0.640000,76.585000,4.190000,5.250000,100.760000,17.220000,2020-08-15 12:00:00,6.000000
75%,2023.000000,272.000000,27.900000,30.170000,26.31000,4.940000,3.790000,81.100000,4.830000,5.980000,101.040000,18.420000,2023-06-08 06:00:00,9.000000
max,2026.000000,366.000000,29.970000,33.930000,28.01000,7.590000,122.650000,91.100000,8.400000,11.740000,101.510000,21.510000,2026-03-31 00:00:00,12.000000
std,3.248907,106.294767,1.325388,1.371155,1.53544,1.102831,8.003947,5.070501,1.059803,1.215018,0.284461,1.881741,NaN,3.477046

In [9]:
duplicates = dataset.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")
if duplicates > 0:
    dataset.drop_duplicates(inplace=True)
    print("Duplicates dropped.")
# Note: df.duplicated() checks entire rows; if duplicates exist, they span all columns.

Number of duplicate rows: 0

In [10]:
numeric_cols = dataset.select_dtypes(include=[np.number]).columns
dataset[numeric_cols].describe()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Month
count,4108.000000,4108.000000,4108.000000,4108.000000,4108.00000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000,4108.000000
mean,2020.131451,180.121227,26.802422,29.163493,25.03813,4.125363,3.740256,77.128038,4.105370,5.189248,100.801130,16.923683,6.423564
std,3.248907,106.294767,1.325388,1.371155,1.53544,1.102831,8.003947,5.070501,1.059803,1.215018,0.284461,1.881741,3.477046
min,2015.000000,1.000000,22.680000,25.410000,20.03000,0.940000,0.000000,60.060000,1.120000,1.550000,100.150000,11.380000,1.000000
25%,2017.000000,86.000000,25.670000,28.090000,23.71000,3.330000,0.110000,73.167500,3.410000,4.377500,100.570000,15.340000,3.000000
50%,2020.000000,179.000000,26.990000,29.080000,25.37500,4.220000,0.640000,76.585000,4.190000,5.250000,100.760000,17.220000,6.000000
75%,2023.000000,272.000000,27.900000,30.170000,26.31000,4.940000,3.790000,81.100000,4.830000,5.980000,101.040000,18.420000,9.000000
max,2026.000000,366.000000,29.970000,33.930000,28.01000,7.590000,122.650000,91.100000,8.400000,11.740000,101.510000,21.510000,12.000000

In [11]:
missing = dataset.isna().sum()
missing_pct = (missing / len(dataset)) * 100
print(missing_pct)
high_missing = missing_pct[missing_pct > 5]
print(f"Columns with >5% missing: {list(high_missing.index)}")
# Interpretation: High missing values (e.g., >5%) may indicate data collection gaps, sensor failures, or regional unavailability, potentially biasing analysis if not handled (e.g., via imputation or exclusion).

YEAR           0.0
DOY            0.0
T2M            0.0
T2M_MAX        0.0
T2M_MIN        0.0
T2M_RANGE      0.0
PRECTOTCORR    0.0
RH2M           0.0
WS2M           0.0
WS2M_MAX       0.0
PS             0.0
QV2M           0.0
country        0.0
Date           0.0
Month          0.0
dtype: float64
Columns with >5% missing: []

In [12]:
cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']
z_scores = (dataset[cols] - dataset[cols].mean()) / dataset[cols].std(ddof=0)
outlier_mask = np.abs(z_scores) > 3
outlier_count = outlier_mask.any(axis=1).sum()

print(f"Rows with |Z| > 3: {outlier_count}")

Rows with |Z| > 3: 97

In [13]:
outlier_rows = dataset[outlier_mask.any(axis=1)]
outlier_rows[['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']].head()

       T2M  T2M_MAX  T2M_MIN  PRECTOTCORR   RH2M  WS2M  WS2M_MAX
78   27.55    28.76    26.78        27.78  85.90  3.93      4.94
112  26.48    27.26    25.85        29.37  88.49  4.78      6.94
123  27.09    28.37    26.18        45.31  86.72  4.36      5.57
124  26.60    28.50    24.91        71.10  87.49  4.17      5.42
126  26.75    28.04    25.98        48.50  88.52  4.61      5.52

In [14]:
weather_cols = ['T2M', 'T2M_MAX', 'T2M_MIN', 'PRECTOTCORR', 'RH2M', 'WS2M', 'WS2M_MAX']
dataset[weather_cols] = dataset[weather_cols].ffill()

In [15]:
threshold = int(0.3 * len(dataset.columns))
dataset = dataset.dropna(thresh=len(dataset.columns) - threshold)

In [16]:
row_missing_pct = dataset.isna().mean(axis=1)
dataset = dataset[row_missing_pct <= 0.30]

In [17]:
dataset.to_csv('../data/tanzania_clean.csv', index=False)